version: 2.0
jobs:
  build:
    docker:
      - image: ruby:2.6.1
    steps:
      - checkout
      - run:
          name: Update RubyGems & Bundler
          command: |
            gem update --system
            gem install bundler
      - run:
          name: Install Dependencies
          command: bin/setup
      - run:
          name: Run Rubocop
          command: bundle exec rubocop
      - run:
          name: Run RSpec
          command: rake spec
